### ISSUE TITLE
Realign KeyError

### ISSUE THREAD

**Issue by hartlama** [iprada/Circle-Map#65]
Hello,

I am running Circle-Map Realign and receive an error message. Here is my output:

/bin/sh: bedtools: command not found
/bin/sh: mergeBed: command not found
[E::idx_find_and_load] Could not retrieve index file for '/scratch/mariacas_root/mariacas99/hartlama/NPA_sorted_qname.bam'
2021-03-22 15:39:40: Realigning reads using Circle-Map

2021-03-22 15:39:40: Clustering structural variant reads

2021-03-22 15:39:40: Splitting clusters to to processors

  0%|          | 0/300 [00:00<?, ?it/s]

0it [00:00, ?it/s][A
  1%|          | 3/300 [00:00<00:10, 27.79it/s]

3it [00:00, 27.93it/s][A
  2%|▏         | 7/300 [00:00<00:09, 32.38it/s]

7it [00:00, 32.45it/s][A
  4%|▎         | 11/300 [00:00<00:08, 35.22it/s]

11it [00:00, 35.26it/s][A
  5%|▌         | 16/300 [00:00<00:07, 36.80it/s]

16it [00:00, 36.80it/s][A
  7%|▋         | 21/300 [00:00<00:07, 38.81it/s]

21it [00:00, 38.82it/s][A
  8%|▊         | 25/300 [00:00<00:07, 36.18it/s]

25it [00:00, 36.20it/s][A
 10%|█         | 30/300 [00:00<00:07, 38.27it/s]

30it [00:00, 38.28it/s][A
 11%|█▏        | 34/300 [00:00<00:07, 38.00it/s]

34it [00:00, 38.01it/s][A
 13%|█▎        | 39/300 [00:01<00:06, 41.32it/s]

39it [00:01, 41.33it/s][A
 15%|█▍        | 44/300 [00:01<00:06, 39.19it/s]

44it [00:01, 39.19it/s][A
 16%|█▌        | 48/300 [00:01<00:06, 39.29it/s]

48it [00:01, 39.29it/s][A
 18%|█▊        | 53/300 [00:01<00:06, 40.25it/s]

53it [00:01, 40.25it/s][A
 19%|█▉        | 58/300 [00:01<00:06, 40.05it/s]

58it [00:01, 40.05it/s][A
 21%|██        | 63/300 [00:01<00:05, 39.95it/s]

63it [00:01, 39.95it/s][A
 23%|██▎       | 68/300 [00:01<00:05, 42.02it/s]

68it [00:01, 42.02it/s][A
 24%|██▍       | 73/300 [00:01<00:05, 40.69it/s]

73it [00:01, 40.69it/s][A
 26%|██▌       | 78/300 [00:02<00:05, 38.99it/s]

78it [00:02, 38.99it/s][A
 27%|██▋       | 82/300 [00:02<00:05, 37.94it/s]

82it [00:02, 37.94it/s][A
 29%|██▉       | 87/300 [00:02<00:05, 38.68it/s]

87it [00:02, 38.67it/s][A
 31%|███       | 92/300 [00:02<00:05, 40.76it/s]

92it [00:02, 40.76it/s][A
 32%|███▏      | 97/300 [00:02<00:05, 39.99it/s]

97it [00:02, 39.99it/s][A
 34%|███▍      | 102/300 [00:02<00:05, 38.90it/s]

102it [00:02, 38.90it/s][A
 36%|███▌      | 107/300 [00:02<00:05, 38.36it/s]

107it [00:02, 38.36it/s][A
 37%|███▋      | 112/300 [00:02<00:04, 40.58it/s]

112it [00:02, 40.57it/s][A
 39%|███▉      | 117/300 [00:02<00:04, 40.21it/s]

117it [00:02, 40.21it/s][A
 41%|████      | 122/300 [00:03<00:04, 40.63it/s]

122it [00:03, 40.63it/s][A
 42%|████▏     | 127/300 [00:03<00:04, 41.45it/s]

127it [00:03, 41.45it/s][A
 44%|████▍     | 132/300 [00:03<00:04, 39.08it/s]

132it [00:03, 39.08it/s][A
 45%|████▌     | 136/300 [00:03<00:04, 39.09it/s]

136it [00:03, 39.09it/s][A
 47%|████▋     | 141/300 [00:03<00:04, 39.71it/s]

141it [00:03, 39.71it/s][A
 49%|████▊     | 146/300 [00:03<00:03, 41.04it/s]

146it [00:03, 41.04it/s][A
 50%|█████     | 151/300 [00:03<00:03, 40.82it/s]

151it [00:03, 40.81it/s][A
 52%|█████▏    | 156/300 [00:03<00:03, 41.06it/s]

156it [00:03, 41.05it/s][A
 54%|█████▎    | 161/300 [00:04<00:03, 40.60it/s]

161it [00:04, 40.60it/s][A
 55%|█████▌    | 166/300 [00:04<00:03, 42.18it/s]

166it [00:04, 42.18it/s][A
 57%|█████▋    | 171/300 [00:04<00:03, 40.95it/s]

171it [00:04, 40.95it/s][A
 59%|█████▊    | 176/300 [00:04<00:02, 41.77it/s]

176it [00:04, 41.77it/s][A
 60%|██████    | 181/300 [00:04<00:02, 41.10it/s]

181it [00:04, 41.10it/s][A
 62%|██████▏   | 186/300 [00:04<00:02, 40.16it/s]

186it [00:04, 40.16it/s][A
 64%|██████▎   | 191/300 [00:04<00:02, 40.76it/s]

191it [00:04, 40.76it/s][A
 65%|██████▌   | 196/300 [00:04<00:02, 40.94it/s]

196it [00:04, 40.94it/s][A
 67%|██████▋   | 201/300 [00:05<00:02, 41.02it/s]

201it [00:05, 41.02it/s][A
 69%|██████▊   | 206/300 [00:05<00:02, 40.98it/s]

206it [00:05, 40.98it/s][A
 70%|███████   | 211/300 [00:05<00:02, 41.35it/s]

211it [00:05, 41.35it/s][A
 72%|███████▏  | 216/300 [00:05<00:02, 40.54it/s]

216it [00:05, 40.52it/s][A
 74%|███████▎  | 221/300 [00:05<00:01, 41.21it/s]

221it [00:05, 41.21it/s][A
 75%|███████▌  | 226/300 [00:05<00:01, 39.83it/s]

226it [00:05, 39.83it/s][A
 77%|███████▋  | 231/300 [00:05<00:01, 39.87it/s]

231it [00:05, 39.87it/s][A
 79%|███████▊  | 236/300 [00:05<00:01, 42.01it/s]

236it [00:05, 42.00it/s][A
 80%|████████  | 241/300 [00:06<00:01, 41.64it/s]

241it [00:06, 41.64it/s][A
 82%|████████▏ | 246/300 [00:06<00:01, 40.68it/s]

246it [00:06, 40.68it/s][A
 84%|████████▎ | 251/300 [00:06<00:01, 40.03it/s]

251it [00:06, 40.02it/s][A
 85%|████████▌ | 256/300 [00:06<00:01, 39.99it/s]

256it [00:06, 39.99it/s][A
 87%|████████▋ | 261/300 [00:06<00:00, 39.90it/s]

261it [00:06, 39.88it/s][A
 88%|████████▊ | 265/300 [00:06<00:00, 39.55it/s]

265it [00:06, 39.56it/s][A
 90%|█████████ | 270/300 [00:06<00:00, 39.10it/s]

270it [00:06, 39.10it/s][A
 92%|█████████▏| 275/300 [00:06<00:00, 41.71it/s]

275it [00:06, 41.69it/s][A
 93%|█████████▎| 280/300 [00:07<00:00, 40.67it/s]

280it [00:07, 40.68it/s][A
 95%|█████████▌| 285/300 [00:07<00:00, 40.55it/s]

285it [00:07, 40.56it/s][A
 97%|█████████▋| 290/300 [00:07<00:00, 38.49it/s]

290it [00:07, 38.49it/s][A
 98%|█████████▊| 295/300 [00:07<00:00, 39.31it/s]

295it [00:07, 39.31it/s][A
100%|██████████| 300/300 [00:07<00:00, 40.57it/s]

300it [00:07, 40.57it/s][A
300it [00:07, 39.98it/s]

100%|██████████| 300/300 [00:07<00:00, 39.97it/s]
2021-03-22 15:39:51: Writting final output to disk
Traceback (most recent call last):
  File "/home/hartlama/.local/bin/Circle-Map", line 33, in <module>
    sys.exit(load_entry_point('Circle-Map==1.1.5', 'console_scripts', 'Circle-Map')())
  File "/home/hartlama/.local/lib/python3.9/site-packages/circlemap/circle_map.py", line 1165, in main
    run = circle_map()
  File "/home/hartlama/.local/lib/python3.9/site-packages/circlemap/circle_map.py", line 187, in __init__
    output = merge_final_output(self.args.sbam, self.args.output, begin, self.args.split,
  File "/home/hartlama/.local/lib/python3.9/site-packages/circlemap/utils.py", line 1266, in merge_final_output
    second_merging_round = unparsed_pd.sort_values(['chrom', 'start', 'end']).reset_index()
  File "/home/hartlama/.local/lib/python3.9/site-packages/pandas/core/frame.py", line 5442, in sort_values
    keys = [self._get_label_or_level_values(x, axis=axis) for x in by]
  File "/home/hartlama/.local/lib/python3.9/site-packages/pandas/core/frame.py", line 5442, in <listcomp>
    keys = [self._get_label_or_level_values(x, axis=axis) for x in by]
  File "/home/hartlama/.local/lib/python3.9/site-packages/pandas/core/generic.py", line 1684, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'chrom'

**Comment by DSchreyer** [comment]
How was this issue resolved in utils.py ? I also run into this error with the github scripts.

**Comment by kotasairohith** [comment]
I am using the Circle-Map 1.1.5 but still getting the same keyError.

2025-09-02 11:28:00: Writting final output to disk
Traceback (most recent call last):
  File "/project/Circle_Map_Test/.venv-circlemap/bin/Circle-Map", line 33, in <module>
    sys.exit(load_entry_point('Circle-Map==1.1.5', 'console_scripts', 'Circle-Map')())
  File "/project/Circle_Map_Test/.venv-circlemap/lib64/python3.9/site-packages/circlemap/circle_map.py", line 1165, in main
    run = circle_map()
  File "/project/Circle_Map_Test/.venv-circlemap/lib64/python3.9/site-packages/circlemap/circle_map.py", line 187, in __init__
    output = merge_final_output(self.args.sbam, self.args.output, begin, self.args.split,
  File "/project/Circle_Map_Test/.venv-circlemap/lib64/python3.9/site-packages/circlemap/utils.py", line 1266, in merge_final_output
    second_merging_round = unparsed_pd.sort_values(['chrom', 'start', 'end']).reset_index()
  File "/project/Circle_Map_Test/.venv-circlemap/lib64/python3.9/site-packages/pandas/core/frame.py", line 7179, in sort_values
    keys = [self._get_label_or_level_values(x, axis=axis) for x in by]
  File "/project/Circle_Map_Test/.venv-circlemap/lib64/python3.9/site-packages/pandas/core/frame.py", line 7179, in <listcomp>
    keys = [self._get_label_or_level_values(x, axis=axis) for x in by]
  File "/project/Circle_Map_Test/.venv-circlemap/lib64/python3.9/site-packages/pandas/core/generic.py", line 1911, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'chrom'
